#include <catch2/catch_test_macros.hpp>
#include <iostream>
#include "adjacencyList.cpp"
using namespace std;

/// String parsing for catch testing
void parseInput(const string input, AdjacencyList &aList) {
    // Collect first line
    string line = input.substr(0, input.find('\n'));
    // Read the number of following lines and the number of power iterations
    int numLines = stoi(line.substr(0, line.find(' ')));
    int numIter = stoi(line.substr(line.find(' ') + 1, line.size() - line.find(' ')));
    // Find the index of the next line
    int nextLineIndex = line.size() + 1;
    // Remove the current line from input and store it at tempInput
    string tempInput = input.substr(nextLineIndex, input.size() - nextLineIndex);
    string from, to;
    // Iterate until all lines have been read
    while(numLines > 0) {
        // Prevent out of range error by ensuring input is never smaller than the next line index
        if(input.size() > nextLineIndex) {
            // Update temp input to remove the current line
            tempInput = input.substr(nextLineIndex, input.size() - nextLineIndex);
            // Isolate current line, collect from and to from it and insert them to the current adjacency list
            line = input.substr(nextLineIndex, tempInput.find('\n'));
            from = line.substr(0, line.find(' '));
            to = line.substr(line.find(' ') + 1, line.size() - line.find(' '));
            aList.insert(from, to);
            // Update the next line index
            nextLineIndex += line.size() + 1;
            // Decrement numLines
            numLines--;
        }
    }
    // Calculate the outdegrees of the current adjacency list
    aList.calculateOutdegrees();
    // Restrict printing from cout, link: https://stackoverflow.com/questions/30184998
    cout.setstate(ios_base::failbit);
    // Process page rank
    aList.PageRank(numIter);
    // Clear cout restriction
    cout.clear();
}

TEST_CASE("PageRank Test 1 - One website points to many", "[2PI]"){

    string input =
R"(10 2
google.com apple.com
google.com NASA.gov
google.com US.gov
google.com ESA.int
google.com JAXA.jp
google.com microsoft.com
google.com yahoo.com
google.com ferrero.it
google.com barillagroup.com
google.com americanairlines.com)";

    string expectedOutput =
R"(ESA.int 0.01
JAXA.jp 0.01
NASA.gov 0.01
US.gov 0.01
americanairlines.com 0.01
apple.com 0.01
barillagroup.com 0.01
ferrero.it 0.01
google.com 0.00
microsoft.com 0.01
yahoo.com 0.01)";

    string actualOutput;

    AdjacencyList t1;
    parseInput(input, t1);
    actualOutput = t1.getStringRepresentation();

    REQUIRE(actualOutput == expectedOutput);
}

TEST_CASE("PageRank Test 2 - Many websites point to one", "[2PI]"){
// Similar to test 1 but testing the reverse

    string input =
R"(10 2
apple.com google.com
NASA.gov google.com
US.gov google.com
ESA.int google.com
JAXA.jp google.com
microsoft.com google.com
yahoo.com google.com
ferrero.it google.com
barillagroup.com google.com
americanairlines.com google.com)";

    string expectedOutput =
R"(ESA.int 0.00
JAXA.jp 0.00
NASA.gov 0.00
US.gov 0.00
americanairlines.com 0.00
apple.com 0.00
barillagroup.com 0.00
ferrero.it 0.00
google.com 0.91
microsoft.com 0.00
yahoo.com 0.00)";

    string actualOutput;

    AdjacencyList t2;
    parseInput(input, t2);
    actualOutput = t2.getStringRepresentation();

    REQUIRE(actualOutput == expectedOutput);

}

// Not working due to setprecision rounding error, but otherwise correct.
TEST_CASE("PageRank Test 3 - Many power iterations", "[300PI]"){

    string input =
R"(5 300
google.com facebook.com
instagram.com facebook.com
ufl.edu instagram.com
ufl.edu google.com
facebook.com ufl.edu)";

    string expectedOutput =
R"(facebook.com 0.25
google.com 0.13
instagram.com 0.13
ufl.edu 0.50)";

    string actualOutput;

    AdjacencyList t3;
    parseInput(input, t3);
    actualOutput = t3.getStringRepresentation();

    REQUIRE(actualOutput == expectedOutput);
}

TEST_CASE("PageRank Test 4 - Many links many power iterations", "[300PI]"){

    string input =
R"(100 300
getbootstrap.com samsung.com
github.com zoom.us
python.org openai.com
google.com roblox.com
stackoverflow.com disney.com
microsoft.com openai.com
google.com python.org
google.com youtube.com
zoom.us openai.com
github.com disney.com
chase.com ufl.edu
samsung.com mozilla.org
chase.com zoom.us
stackoverflow.com google.com
google.com apple.com
python.org mozilla.org
openai.com python.org
instagram.com weather.com
reactjs.org aman.com
roblox.com python.org
instagram.com google.com
aman.com twitter.com
mozilla.org stackoverflow.com
microsoft.com disney.com
apple.com google.com
ufl.edu microsoft.com
apple.com aman.com
stackoverflow.com youtube.com
disney.com twitter.com
reactjs.org getbootstrap.com
twitter.com weather.com
roblox.com stackoverflow.com
aman.com reactjs.org
zoom.us stackoverflow.com
weather.com github.com
openai.com twitter.com
instagram.com stackoverflow.com
disney.com google.com
apple.com getbootstrap.com
apple.com chase.com
twitter.com pcbuildinguf.com
reactjs.org github.com
chase.com google.com
reactjs.org microsoft.com
roblox.com openai.com
aman.com openai.com
pcbuildinguf.com getbootstrap.com
weather.com ufl.edu
zoom.us pcbuildinguf.com
roblox.com getbootstrap.com
github.com youtube.com
chase.com weather.com
samsung.com google.com
ufl.edu aman.com
getbootstrap.com roblox.com
disney.com youtube.com
roblox.com disney.com
reactjs.org python.org
zoom.us twitter.com
microsoft.com twitter.com
microsoft.com python.org
reactjs.org zoom.us
samsung.com zoom.us
roblox.com google.com
aman.com ufl.edu
github.com samsung.com
apple.com microsoft.com
samsung.com youtube.com
apple.com samsung.com
openai.com weather.com
openai.com microsoft.com
samsung.com aman.com
python.org samsung.com
getbootstrap.com youtube.com
zoom.us chase.com
instagram.com youtube.com
reactjs.org mozilla.org
youtube.com apple.com
twitter.com instagram.com
getbootstrap.com python.org
weather.com youtube.com
weather.com openai.com
youtube.com ufl.edu
roblox.com samsung.com
youtube.com github.com
samsung.com github.com
microsoft.com google.com
instagram.com mozilla.org
weather.com disney.com
aman.com samsung.com
getbootstrap.com apple.com
mozilla.org youtube.com
ufl.edu chase.com
twitter.com microsoft.com
chase.com pcbuildinguf.com
mozilla.org aman.com
twitter.com python.org
microsoft.com aman.com
reactjs.org ufl.edu
aman.com pcbuildinguf.com)";

    string expectedOutput =
R"(aman.com 0.06
apple.com 0.06
chase.com 0.03
disney.com 0.04
getbootstrap.com 0.05
github.com 0.05
google.com 0.06
instagram.com 0.01
microsoft.com 0.05
mozilla.org 0.04
openai.com 0.06
pcbuildinguf.com 0.03
python.org 0.06
reactjs.org 0.01
roblox.com 0.03
samsung.com 0.07
stackoverflow.com 0.02
twitter.com 0.05
ufl.edu 0.06
weather.com 0.03
youtube.com 0.09
zoom.us 0.03)";

    string actualOutput;

    AdjacencyList t4;
    parseInput(input, t4);
    actualOutput = t4.getStringRepresentation();

    REQUIRE(actualOutput == expectedOutput);
}

TEST_CASE("PageRank Test 5 - Dense Undirected Graph", "[5PI]"){

    string input =
R"(30 5
google.com apple.com
apple.com google.com
google.com microsoft.com
microsoft.com google.com
google.com zoom.us
zoom.us google.com
google.com ufl.edu
ufl.edu google.com
google.com bootstrap.com
bootstrap.com google.com
apple.com bootstrap.com
bootstrap.com apple.com
apple.com ufl.com
ufl.com apple.com
apple.com zoom.us
zoom.us apple.com
apple.com microsoft.com
microsoft.com apple.com
microsoft.com bootstrap.com
bootstrap.com microsoft.com
microsoft.com ufl.edu
ufl.edu microsoft.com
microsoft.com zoom.us
zoom.us microsoft.com
zoom.us bootstrap.com
bootstrap.com zoom.us
zoom.us ufl.edu
ufl.edu zoom.us
ufl.edu bootstrap.com
bootstrap.com ufl.edu)";

    string expectedOutput =
R"(apple.com 0.16
bootstrap.com 0.17
google.com 0.17
microsoft.com 0.17
ufl.com 0.04
ufl.edu 0.13
zoom.us 0.17)";

    string actualOutput;

    AdjacencyList t5;
    parseInput(input, t5);
    actualOutput = t5.getStringRepresentation();

    REQUIRE(actualOutput == expectedOutput);
}

// Same problem as test case 3, rounding issue with setprecision
TEST_CASE("PageRank Test 6 - 1000 edges", "[2PI]"){

    string input =
R"(1000 2
youtube.com zoom.us
zoom.us youtube.com
samsung.com stackoverflow.com
apple.com samsung.com
zoom.us getbootstrap.com
disney.com apple.com
python.org ufl.edu
google.com chase.com
openai.com stackoverflow.com
wikipedia.org pcbuildinguf.com
samsung.com openai.com
stackoverflow.com youtube.com
disney.com youtube.com
apple.com disney.com
samsung.com mozilla.org
ufl.edu getbootstrap.com
aman.com wikipedia.org
aman.com openai.com
pcbuildinguf.com weather.com
chase.com wikipedia.org
google.com youtube.com
wikipedia.org stackoverflow.com
wikipedia.org weather.com
chase.com python.org
apple.com openai.com
ufl.edu stackoverflow.com
ufl.edu google.com
stackoverflow.com chase.com
zoom.us openai.com
mozilla.org openai.com
weather.com samsung.com
facebook.com python.org
samsung.com microsoft.com
google.com getbootstrap.com
apple.com stackoverflow.com
microsoft.com zoom.us
google.com zoom.us
openai.com disney.com
ufl.edu apple.com
pcbuildinguf.com samsung.com
python.org stackoverflow.com
google.com mozilla.org
apple.com aman.com
mozilla.org google.com
apple.com python.org
getbootstrap.com stackoverflow.com
pcbuildinguf.com stackoverflow.com
chase.com facebook.com
chase.com youtube.com
chase.com disney.com
microsoft.com disney.com
microsoft.com weather.com
disney.com facebook.com
python.org samsung.com
stackoverflow.com facebook.com
pcbuildinguf.com openai.com
chase.com zoom.us
stackoverflow.com mozilla.org
weather.com mozilla.org
pcbuildinguf.com aman.com
youtube.com openai.com
samsung.com wikipedia.org
weather.com chase.com
pcbuildinguf.com chase.com
samsung.com weather.com
mozilla.org ufl.edu
youtube.com wikipedia.org
weather.com microsoft.com
ufl.edu microsoft.com
zoom.us disney.com
chase.com weather.com
wikipedia.org disney.com
aman.com mozilla.org
samsung.com facebook.com
samsung.com apple.com
stackoverflow.com ufl.edu
python.org disney.com
weather.com stackoverflow.com
mozilla.org zoom.us
weather.com youtube.com
microsoft.com samsung.com
youtube.com python.org
python.org pcbuildinguf.com
openai.com apple.com
ufl.edu youtube.com
python.org openai.com
aman.com microsoft.com
mozilla.org microsoft.com
aman.com google.com
openai.com pcbuildinguf.com
aman.com facebook.com
microsoft.com wikipedia.org
samsung.com google.com
apple.com google.com
weather.com apple.com
zoom.us mozilla.org
getbootstrap.com facebook.com
weather.com wikipedia.org
pcbuildinguf.com facebook.com
zoom.us apple.com
python.org youtube.com
mozilla.org pcbuildinguf.com
samsung.com aman.com
youtube.com chase.com
google.com samsung.com
roblox.com disney.com
microsoft.com samsung.com
apple.com facebook.com
apple.com roblox.com
microsoft.com github.com
github.com samsung.com
microsoft.com disney.com
weather.com disney.com
disney.com reactjs.org
reactjs.org roblox.com
github.com aman.com
disney.com facebook.com
microsoft.com roblox.com
samsung.com weather.com
openai.com apple.com
apple.com github.com
google.com facebook.com
ufl.edu aman.com
facebook.com aman.com
instagram.com openai.com
chase.com disney.com
microsoft.com chase.com
disney.com roblox.com
roblox.com reactjs.org
microsoft.com apple.com
instagram.com weather.com
samsung.com microsoft.com
weather.com apple.com
google.com ufl.edu
github.com ufl.edu
chase.com facebook.com
aman.com weather.com
roblox.com ufl.edu
chase.com ufl.edu
weather.com github.com
github.com facebook.com
microsoft.com openai.com
disney.com openai.com
roblox.com google.com
reactjs.org microsoft.com
google.com microsoft.com
ufl.edu apple.com
weather.com samsung.com
openai.com instagram.com
reactjs.org openai.com
reactjs.org samsung.com
apple.com ufl.edu
samsung.com instagram.com
roblox.com aman.com
disney.com samsung.com
github.com chase.com
google.com instagram.com
chase.com openai.com
openai.com microsoft.com
ufl.edu openai.com
weather.com chase.com
disney.com apple.com
ufl.edu chase.com
weather.com roblox.com
ufl.edu facebook.com
instagram.com google.com
chase.com instagram.com
instagram.com ufl.edu
google.com disney.com
disney.com microsoft.com
weather.com instagram.com
disney.com chase.com
github.com roblox.com
facebook.com microsoft.com
facebook.com reactjs.org
apple.com aman.com
roblox.com openai.com
microsoft.com google.com
google.com chase.com
apple.com getbootstrap.com
weather.com google.com
microsoft.com instagram.com
disney.com samsung.com
zoom.us github.com
weather.com instagram.com
aman.com zoom.us
apple.com youtube.com
getbootstrap.com roblox.com
facebook.com samsung.com
youtube.com zoom.us
facebook.com google.com
roblox.com youtube.com
youtube.com twitter.com
wikipedia.org roblox.com
github.com openai.com
github.com twitter.com
wikipedia.org aman.com
roblox.com twitter.com
zoom.us weather.com
apple.com aman.com
aman.com microsoft.com
instagram.com google.com
wikipedia.org zoom.us
github.com python.org
google.com zoom.us
disney.com getbootstrap.com
aman.com python.org
google.com openai.com
disney.com apple.com
youtube.com instagram.com
wikipedia.org disney.com
google.com github.com
microsoft.com github.com
instagram.com openai.com
zoom.us python.org
getbootstrap.com openai.com
openai.com google.com
google.com getbootstrap.com
instagram.com microsoft.com
wikipedia.org samsung.com
openai.com samsung.com
github.com disney.com
roblox.com wikipedia.org
wikipedia.org getbootstrap.com
instagram.com apple.com
python.org apple.com
getbootstrap.com github.com
aman.com twitter.com
youtube.com facebook.com
github.com facebook.com
microsoft.com facebook.com
samsung.com weather.com
openai.com getbootstrap.com
aman.com getbootstrap.com
github.com samsung.com
apple.com microsoft.com
instagram.com samsung.com
youtube.com wikipedia.org
github.com weather.com
aman.com roblox.com
samsung.com disney.com
roblox.com google.com
getbootstrap.com microsoft.com
github.com apple.com
github.com wikipedia.org
weather.com samsung.com
facebook.com instagram.com
getbootstrap.com facebook.com
openai.com facebook.com
microsoft.com roblox.com
getbootstrap.com google.com
microsoft.com disney.com
openai.com twitter.com
wikipedia.org instagram.com
instagram.com facebook.com
samsung.com aman.com
roblox.com weather.com
microsoft.com google.com
aman.com facebook.com
disney.com zoom.us
wikipedia.org microsoft.com
roblox.com samsung.com
instagram.com wikipedia.org
facebook.com roblox.com
python.org instagram.com
twitter.com github.com
youtube.com apple.com
samsung.com apple.com
microsoft.com samsung.com
apple.com wikipedia.org
facebook.com python.org
google.com ufl.edu
reactjs.org ufl.edu
weather.com roblox.com
reactjs.org zoom.us
stackoverflow.com github.com
pcbuildinguf.com aman.com
python.org apple.com
microsoft.com twitter.com
facebook.com apple.com
youtube.com facebook.com
aman.com github.com
chase.com facebook.com
reactjs.org wikipedia.org
twitter.com weather.com
chase.com twitter.com
github.com weather.com
apple.com roblox.com
python.org github.com
youtube.com twitter.com
weather.com microsoft.com
apple.com wikipedia.org
github.com python.org
zoom.us facebook.com
google.com facebook.com
ufl.edu python.org
zoom.us wikipedia.org
ufl.edu wikipedia.org
roblox.com aman.com
reactjs.org roblox.com
apple.com pcbuildinguf.com
ufl.edu microsoft.com
apple.com chase.com
chase.com apple.com
chase.com python.org
weather.com pcbuildinguf.com
weather.com reactjs.org
aman.com ufl.edu
ufl.edu reactjs.org
ufl.edu zoom.us
twitter.com facebook.com
weather.com aman.com
stackoverflow.com pcbuildinguf.com
pcbuildinguf.com python.org
github.com twitter.com
google.com chase.com
github.com reactjs.org
github.com facebook.com
stackoverflow.com facebook.com
stackoverflow.com ufl.edu
reactjs.org facebook.com
google.com reactjs.org
zoom.us youtube.com
ufl.edu twitter.com
microsoft.com roblox.com
zoom.us pcbuildinguf.com
facebook.com wikipedia.org
pcbuildinguf.com ufl.edu
microsoft.com python.org
facebook.com chase.com
twitter.com google.com
google.com roblox.com
youtube.com python.org
wikipedia.org zoom.us
github.com chase.com
google.com github.com
apple.com twitter.com
roblox.com facebook.com
zoom.us python.org
aman.com weather.com
microsoft.com reactjs.org
google.com aman.com
aman.com apple.com
ufl.edu apple.com
weather.com zoom.us
chase.com weather.com
reactjs.org chase.com
wikipedia.org youtube.com
weather.com twitter.com
weather.com python.org
python.org twitter.com
python.org chase.com
twitter.com zoom.us
python.org microsoft.com
reactjs.org apple.com
roblox.com github.com
wikipedia.org stackoverflow.com
github.com wikipedia.org
apple.com ufl.edu
reactjs.org youtube.com
youtube.com github.com
microsoft.com aman.com
weather.com youtube.com
github.com ufl.edu
youtube.com reactjs.org
roblox.com ufl.edu
chase.com youtube.com
zoom.us reactjs.org
aman.com pcbuildinguf.com
zoom.us github.com
stackoverflow.com zoom.us
facebook.com aman.com
google.com python.org
twitter.com wikipedia.org
twitter.com microsoft.com
microsoft.com weather.com
weather.com apple.com
pcbuildinguf.com stackoverflow.com
apple.com youtube.com
pcbuildinguf.com apple.com
chase.com google.com
youtube.com aman.com
twitter.com apple.com
pcbuildinguf.com google.com
python.org roblox.com
facebook.com google.com
roblox.com reactjs.org
python.org google.com
roblox.com youtube.com
youtube.com zoom.us
youtube.com zoom.us
samsung.com stackoverflow.com
apple.com samsung.com
zoom.us getbootstrap.com
disney.com apple.com
python.org ufl.edu
google.com chase.com
openai.com stackoverflow.com
wikipedia.org pcbuildinguf.com
samsung.com openai.com
stackoverflow.com youtube.com
disney.com youtube.com
apple.com disney.com
samsung.com mozilla.org
ufl.edu getbootstrap.com
aman.com wikipedia.org
aman.com openai.com
pcbuildinguf.com weather.com
chase.com wikipedia.org
google.com youtube.com
wikipedia.org stackoverflow.com
wikipedia.org weather.com
chase.com python.org
apple.com openai.com
ufl.edu stackoverflow.com
ufl.edu google.com
stackoverflow.com chase.com
zoom.us openai.com
mozilla.org openai.com
weather.com samsung.com
facebook.com python.org
samsung.com microsoft.com
google.com getbootstrap.com
apple.com stackoverflow.com
microsoft.com zoom.us
google.com zoom.us
openai.com disney.com
ufl.edu apple.com
pcbuildinguf.com samsung.com
python.org stackoverflow.com
google.com mozilla.org
apple.com aman.com
mozilla.org google.com
apple.com python.org
getbootstrap.com stackoverflow.com
pcbuildinguf.com stackoverflow.com
chase.com facebook.com
chase.com youtube.com
chase.com disney.com
microsoft.com disney.com
microsoft.com weather.com
disney.com facebook.com
python.org samsung.com
stackoverflow.com facebook.com
pcbuildinguf.com openai.com
chase.com zoom.us
stackoverflow.com mozilla.org
weather.com mozilla.org
pcbuildinguf.com aman.com
youtube.com openai.com
samsung.com wikipedia.org
weather.com chase.com
pcbuildinguf.com chase.com
samsung.com weather.com
mozilla.org ufl.edu
youtube.com wikipedia.org
weather.com microsoft.com
ufl.edu microsoft.com
zoom.us disney.com
chase.com weather.com
wikipedia.org disney.com
aman.com mozilla.org
samsung.com facebook.com
samsung.com apple.com
stackoverflow.com ufl.edu
python.org disney.com
weather.com stackoverflow.com
mozilla.org zoom.us
weather.com youtube.com
microsoft.com samsung.com
youtube.com python.org
python.org pcbuildinguf.com
openai.com apple.com
ufl.edu youtube.com
python.org openai.com
aman.com microsoft.com
mozilla.org microsoft.com
aman.com google.com
openai.com pcbuildinguf.com
aman.com facebook.com
microsoft.com wikipedia.org
samsung.com google.com
apple.com google.com
weather.com apple.com
zoom.us mozilla.org
getbootstrap.com facebook.com
weather.com wikipedia.org
pcbuildinguf.com facebook.com
zoom.us apple.com
python.org youtube.com
mozilla.org pcbuildinguf.com
samsung.com aman.com
youtube.com chase.com
google.com samsung.com
roblox.com disney.com
microsoft.com samsung.com
apple.com facebook.com
apple.com roblox.com
microsoft.com github.com
github.com samsung.com
microsoft.com disney.com
weather.com disney.com
disney.com reactjs.org
reactjs.org roblox.com
github.com aman.com
disney.com facebook.com
microsoft.com roblox.com
samsung.com weather.com
openai.com apple.com
apple.com github.com
google.com facebook.com
ufl.edu aman.com
facebook.com aman.com
instagram.com openai.com
chase.com disney.com
microsoft.com chase.com
disney.com roblox.com
roblox.com reactjs.org
microsoft.com apple.com
instagram.com weather.com
samsung.com microsoft.com
weather.com apple.com
google.com ufl.edu
github.com ufl.edu
chase.com facebook.com
aman.com weather.com
roblox.com ufl.edu
chase.com ufl.edu
weather.com github.com
github.com facebook.com
microsoft.com openai.com
disney.com openai.com
roblox.com google.com
reactjs.org microsoft.com
google.com microsoft.com
ufl.edu apple.com
weather.com samsung.com
openai.com instagram.com
reactjs.org openai.com
reactjs.org samsung.com
apple.com ufl.edu
samsung.com instagram.com
roblox.com aman.com
disney.com samsung.com
github.com chase.com
google.com instagram.com
chase.com openai.com
openai.com microsoft.com
ufl.edu openai.com
weather.com chase.com
disney.com apple.com
ufl.edu chase.com
weather.com roblox.com
ufl.edu facebook.com
instagram.com google.com
chase.com instagram.com
instagram.com ufl.edu
google.com disney.com
disney.com microsoft.com
weather.com instagram.com
disney.com chase.com
github.com roblox.com
facebook.com microsoft.com
facebook.com reactjs.org
apple.com aman.com
roblox.com openai.com
microsoft.com google.com
google.com chase.com
apple.com getbootstrap.com
weather.com google.com
microsoft.com instagram.com
disney.com samsung.com
zoom.us github.com
weather.com instagram.com
aman.com zoom.us
apple.com youtube.com
getbootstrap.com roblox.com
facebook.com samsung.com
youtube.com zoom.us
facebook.com google.com
roblox.com youtube.com
youtube.com twitter.com
wikipedia.org roblox.com
github.com openai.com
github.com twitter.com
wikipedia.org aman.com
roblox.com twitter.com
zoom.us weather.com
apple.com aman.com
aman.com microsoft.com
instagram.com google.com
wikipedia.org zoom.us
github.com python.org
google.com zoom.us
disney.com getbootstrap.com
aman.com python.org
google.com openai.com
disney.com apple.com
youtube.com instagram.com
wikipedia.org disney.com
google.com github.com
microsoft.com github.com
instagram.com openai.com
zoom.us python.org
getbootstrap.com openai.com
openai.com google.com
google.com getbootstrap.com
instagram.com microsoft.com
wikipedia.org samsung.com
openai.com samsung.com
github.com disney.com
roblox.com wikipedia.org
wikipedia.org getbootstrap.com
instagram.com apple.com
python.org apple.com
getbootstrap.com github.com
aman.com twitter.com
youtube.com facebook.com
github.com facebook.com
microsoft.com facebook.com
samsung.com weather.com
openai.com getbootstrap.com
aman.com getbootstrap.com
github.com samsung.com
apple.com microsoft.com
instagram.com samsung.com
youtube.com wikipedia.org
github.com weather.com
aman.com roblox.com
samsung.com disney.com
roblox.com google.com
getbootstrap.com microsoft.com
github.com apple.com
github.com wikipedia.org
weather.com samsung.com
facebook.com instagram.com
getbootstrap.com facebook.com
openai.com facebook.com
microsoft.com roblox.com
getbootstrap.com google.com
microsoft.com disney.com
openai.com twitter.com
wikipedia.org instagram.com
instagram.com facebook.com
samsung.com aman.com
roblox.com weather.com
microsoft.com google.com
aman.com facebook.com
disney.com zoom.us
wikipedia.org microsoft.com
roblox.com samsung.com
instagram.com wikipedia.org
facebook.com roblox.com
python.org instagram.com
twitter.com github.com
youtube.com apple.com
samsung.com apple.com
microsoft.com samsung.com
apple.com wikipedia.org
facebook.com python.org
google.com ufl.edu
reactjs.org ufl.edu
weather.com roblox.com
reactjs.org zoom.us
stackoverflow.com github.com
pcbuildinguf.com aman.com
python.org apple.com
microsoft.com twitter.com
facebook.com apple.com
youtube.com facebook.com
aman.com github.com
chase.com facebook.com
reactjs.org wikipedia.org
twitter.com weather.com
chase.com twitter.com
github.com weather.com
apple.com roblox.com
python.org github.com
youtube.com twitter.com
weather.com microsoft.com
apple.com wikipedia.org
github.com python.org
zoom.us facebook.com
google.com facebook.com
ufl.edu python.org
zoom.us wikipedia.org
ufl.edu wikipedia.org
roblox.com aman.com
reactjs.org roblox.com
apple.com pcbuildinguf.com
ufl.edu microsoft.com
apple.com chase.com
chase.com apple.com
chase.com python.org
weather.com pcbuildinguf.com
weather.com reactjs.org
aman.com ufl.edu
ufl.edu reactjs.org
ufl.edu zoom.us
twitter.com facebook.com
weather.com aman.com
stackoverflow.com pcbuildinguf.com
pcbuildinguf.com python.org
github.com twitter.com
google.com chase.com
github.com reactjs.org
github.com facebook.com
stackoverflow.com facebook.com
stackoverflow.com ufl.edu
reactjs.org facebook.com
google.com reactjs.org
zoom.us youtube.com
ufl.edu twitter.com
microsoft.com roblox.com
zoom.us pcbuildinguf.com
facebook.com wikipedia.org
pcbuildinguf.com ufl.edu
microsoft.com python.org
facebook.com chase.com
twitter.com google.com
google.com roblox.com
youtube.com python.org
wikipedia.org zoom.us
github.com chase.com
google.com github.com
apple.com twitter.com
roblox.com facebook.com
zoom.us python.org
aman.com weather.com
microsoft.com reactjs.org
google.com aman.com
aman.com apple.com
ufl.edu apple.com
weather.com zoom.us
chase.com weather.com
reactjs.org chase.com
wikipedia.org youtube.com
weather.com twitter.com
weather.com python.org
python.org twitter.com
python.org chase.com
twitter.com zoom.us
python.org microsoft.com
reactjs.org apple.com
roblox.com github.com
wikipedia.org stackoverflow.com
github.com wikipedia.org
apple.com ufl.edu
reactjs.org youtube.com
youtube.com github.com
microsoft.com aman.com
weather.com youtube.com
github.com ufl.edu
youtube.com reactjs.org
roblox.com ufl.edu
chase.com youtube.com
zoom.us reactjs.org
aman.com pcbuildinguf.com
zoom.us github.com
stackoverflow.com zoom.us
facebook.com aman.com
google.com python.org
twitter.com wikipedia.org
twitter.com microsoft.com
microsoft.com weather.com
weather.com apple.com
pcbuildinguf.com stackoverflow.com
apple.com youtube.com
pcbuildinguf.com apple.com
chase.com google.com
youtube.com aman.com
twitter.com apple.com
pcbuildinguf.com google.com
python.org roblox.com
facebook.com google.com
roblox.com reactjs.org
python.org google.com
roblox.com youtube.com
youtube.com zoom.us
youtube.com zoom.us
samsung.com stackoverflow.com
apple.com samsung.com
zoom.us getbootstrap.com
disney.com apple.com
python.org ufl.edu
google.com chase.com
openai.com stackoverflow.com
wikipedia.org pcbuildinguf.com
samsung.com openai.com
stackoverflow.com youtube.com
disney.com youtube.com
apple.com disney.com
samsung.com mozilla.org
ufl.edu getbootstrap.com
aman.com wikipedia.org
aman.com openai.com
pcbuildinguf.com weather.com
chase.com wikipedia.org
google.com youtube.com
wikipedia.org stackoverflow.com
wikipedia.org weather.com
chase.com python.org
apple.com openai.com
ufl.edu stackoverflow.com
ufl.edu google.com
stackoverflow.com chase.com
zoom.us openai.com
mozilla.org openai.com
weather.com samsung.com
facebook.com python.org
samsung.com microsoft.com
google.com getbootstrap.com
apple.com stackoverflow.com
microsoft.com zoom.us
google.com zoom.us
openai.com disney.com
ufl.edu apple.com
pcbuildinguf.com samsung.com
python.org stackoverflow.com
google.com mozilla.org
apple.com aman.com
mozilla.org google.com
apple.com python.org
getbootstrap.com stackoverflow.com
pcbuildinguf.com stackoverflow.com
chase.com facebook.com
chase.com youtube.com
chase.com disney.com
microsoft.com disney.com
microsoft.com weather.com
disney.com facebook.com
python.org samsung.com
stackoverflow.com facebook.com
pcbuildinguf.com openai.com
chase.com zoom.us
stackoverflow.com mozilla.org
weather.com mozilla.org
pcbuildinguf.com aman.com
youtube.com openai.com
samsung.com wikipedia.org
weather.com chase.com
pcbuildinguf.com chase.com
samsung.com weather.com
mozilla.org ufl.edu
youtube.com wikipedia.org
weather.com microsoft.com
ufl.edu microsoft.com
zoom.us disney.com
chase.com weather.com
wikipedia.org disney.com
aman.com mozilla.org
samsung.com facebook.com
samsung.com apple.com
stackoverflow.com ufl.edu
python.org disney.com
weather.com stackoverflow.com
mozilla.org zoom.us
weather.com youtube.com
microsoft.com samsung.com
youtube.com python.org
python.org pcbuildinguf.com
openai.com apple.com
ufl.edu youtube.com
python.org openai.com
aman.com microsoft.com
mozilla.org microsoft.com
aman.com google.com
openai.com pcbuildinguf.com
aman.com facebook.com
microsoft.com wikipedia.org
samsung.com google.com
apple.com google.com
weather.com apple.com
zoom.us mozilla.org
getbootstrap.com facebook.com
weather.com wikipedia.org
pcbuildinguf.com facebook.com
zoom.us apple.com
python.org youtube.com
mozilla.org pcbuildinguf.com
samsung.com aman.com
youtube.com chase.com
google.com samsung.com
roblox.com disney.com
microsoft.com samsung.com
apple.com facebook.com
apple.com roblox.com
microsoft.com github.com
github.com samsung.com
microsoft.com disney.com
weather.com disney.com
disney.com reactjs.org
reactjs.org roblox.com
github.com aman.com
disney.com facebook.com
microsoft.com roblox.com
samsung.com weather.com
openai.com apple.com
apple.com github.com
google.com facebook.com
ufl.edu aman.com
facebook.com aman.com
instagram.com openai.com
chase.com disney.com
microsoft.com chase.com
disney.com roblox.com
roblox.com reactjs.org
microsoft.com apple.com
instagram.com weather.com
samsung.com microsoft.com
weather.com apple.com
google.com ufl.edu
github.com ufl.edu
chase.com facebook.com
aman.com weather.com
roblox.com ufl.edu
chase.com ufl.edu
weather.com github.com
github.com facebook.com
microsoft.com openai.com
disney.com openai.com
roblox.com google.com
reactjs.org microsoft.com
google.com microsoft.com
ufl.edu apple.com
weather.com samsung.com
openai.com instagram.com
reactjs.org openai.com
reactjs.org samsung.com
apple.com ufl.edu
samsung.com instagram.com
roblox.com aman.com
disney.com samsung.com
github.com chase.com
google.com instagram.com
chase.com openai.com
openai.com microsoft.com
ufl.edu openai.com
weather.com chase.com
disney.com apple.com
ufl.edu chase.com
weather.com roblox.com
ufl.edu facebook.com
instagram.com google.com
chase.com instagram.com
instagram.com ufl.edu
google.com disney.com
disney.com microsoft.com
weather.com instagram.com
disney.com chase.com
github.com roblox.com
facebook.com microsoft.com
facebook.com reactjs.org
apple.com aman.com
roblox.com openai.com
microsoft.com google.com
google.com chase.com
apple.com getbootstrap.com
weather.com google.com
microsoft.com instagram.com
disney.com samsung.com
zoom.us github.com
weather.com instagram.com
aman.com zoom.us
apple.com youtube.com
getbootstrap.com roblox.com
facebook.com samsung.com
youtube.com zoom.us
facebook.com google.com
roblox.com youtube.com
youtube.com twitter.com
wikipedia.org roblox.com
github.com openai.com
github.com twitter.com
wikipedia.org aman.com
roblox.com twitter.com
zoom.us weather.com
apple.com aman.com
aman.com microsoft.com
instagram.com google.com
wikipedia.org zoom.us
github.com python.org
google.com zoom.us
disney.com getbootstrap.com
aman.com python.org
google.com openai.com
disney.com apple.com
youtube.com instagram.com
wikipedia.org disney.com
google.com github.com
microsoft.com github.com
instagram.com openai.com
zoom.us python.org
getbootstrap.com openai.com
openai.com google.com
google.com getbootstrap.com
instagram.com microsoft.com
wikipedia.org samsung.com
openai.com samsung.com
github.com disney.com)";

    string expectedOutput =
R"(aman.com 0.04
apple.com 0.06
chase.com 0.04
disney.com 0.04
facebook.com 0.07
getbootstrap.com 0.02
github.com 0.04
google.com 0.06
instagram.com 0.03
microsoft.com 0.06
mozilla.org 0.02
openai.com 0.06
pcbuildinguf.com 0.03
python.org 0.04
reactjs.org 0.03
roblox.com 0.04
samsung.com 0.05
stackoverflow.com 0.03
twitter.com 0.03
ufl.edu 0.04
weather.com 0.04
wikipedia.org 0.05
youtube.com 0.04
zoom.us 0.05)";

    string actualOutput;

    AdjacencyList t6;
    parseInput(input, t6);
    actualOutput = t6.getStringRepresentation();

    REQUIRE(actualOutput == expectedOutput);
}